name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - staging
          - production
        required: true
        description: Entorno de despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy artefacto
        run: |
          echo "Desplegando a ${{ github.event.inputs.environment }}"
          # Aquí se invocaría el pipeline/CD real (SSH, Kubernetes, etc.)
